[2025-03-30T20:45:37.928+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T20:45:37.941+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.ingest_sales_data manual__2025-03-30T20:45:36.809266+00:00 [queued]>
[2025-03-30T20:45:37.946+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.ingest_sales_data manual__2025-03-30T20:45:36.809266+00:00 [queued]>
[2025-03-30T20:45:37.947+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T20:45:37.954+0000] {taskinstance.py:2890} INFO - Executing <Task(SalesIngestionOperator): ingest_sales_data> on 2025-03-30 20:45:36.809266+00:00
[2025-03-30T20:45:37.962+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T20:45:37.961+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'ingest_sales_data', 'manual__2025-03-30T20:45:36.809266+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmpycuzy7rm']
[2025-03-30T20:45:37.963+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-03-30T20:45:37.963+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask ingest_sales_data
[2025-03-30T20:45:38.001+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.ingest_sales_data manual__2025-03-30T20:45:36.809266+00:00 [running]> on host 96d9f0139b31
[2025-03-30T20:45:38.060+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='ingest_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T20:45:36.809266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T20:45:36.809266+00:00'
[2025-03-30T20:45:38.061+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T20:45:38.086+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (LocalFilesystemBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 317, in get_connection
    if conn_id in self._local_connections:
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 314, in _local_connections
    return load_connections_dict(self.connections_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 266, in load_connections_dict
    secrets: dict[str, Any] = _parse_secret_file(file_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 163, in _parse_secret_file
    raise AirflowException(
airflow.exceptions.AirflowException: File /opt/secrets/connections.yaml was not found. Check the configuration of your Secrets backend.
[2025-03-30T20:45:38.096+0000] {base.py:84} INFO - Retrieving connection 'db'
[2025-03-30T20:45:38.106+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/SalesIngestionPlugin.py", line 41, in execute
    self._prepare_db()
  File "/opt/airflow/plugins/SalesIngestionPlugin.py", line 106, in _prepare_db
    cursor.commit()
    ^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'commit'
[2025-03-30T20:45:38.115+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sales_data, task_id=ingest_sales_data, run_id=manual__2025-03-30T20:45:36.809266+00:00, execution_date=20250330T204536, start_date=20250330T204537, end_date=20250330T204538
[2025-03-30T20:45:38.140+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T20:45:38.141+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task ingest_sales_data ('psycopg2.extensions.cursor' object has no attribute 'commit'; 215)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/SalesIngestionPlugin.py", line 41, in execute
    self._prepare_db()
  File "/opt/airflow/plugins/SalesIngestionPlugin.py", line 106, in _prepare_db
    cursor.commit()
    ^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'commit'
[2025-03-30T20:45:38.178+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T20:45:38.194+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T20:45:38.195+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
