[2025-03-30T20:31:41.588+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T20:31:41.600+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.ingest_sales_data manual__2025-03-30T20:31:40.910558+00:00 [queued]>
[2025-03-30T20:31:41.604+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.ingest_sales_data manual__2025-03-30T20:31:40.910558+00:00 [queued]>
[2025-03-30T20:31:41.604+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T20:31:41.609+0000] {taskinstance.py:2890} INFO - Executing <Task(SalesIngestionOperator): ingest_sales_data> on 2025-03-30 20:31:40.910558+00:00
[2025-03-30T20:31:41.616+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T20:31:41.616+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-03-30T20:31:41.615+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'ingest_sales_data', 'manual__2025-03-30T20:31:40.910558+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmpbjv59hnr']
[2025-03-30T20:31:41.617+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask ingest_sales_data
[2025-03-30T20:31:41.661+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.ingest_sales_data manual__2025-03-30T20:31:40.910558+00:00 [running]> on host 45ab37a7d7f0
[2025-03-30T20:31:41.720+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='ingest_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T20:31:40.910558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T20:31:40.910558+00:00'
[2025-03-30T20:31:41.721+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T20:31:41.744+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (LocalFilesystemBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 317, in get_connection
    if conn_id in self._local_connections:
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 314, in _local_connections
    return load_connections_dict(self.connections_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 266, in load_connections_dict
    secrets: dict[str, Any] = _parse_secret_file(file_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 163, in _parse_secret_file
    raise AirflowException(
airflow.exceptions.AirflowException: File /opt/secrets/connections.yaml was not found. Check the configuration of your Secrets backend.
[2025-03-30T20:31:41.753+0000] {base.py:84} INFO - Retrieving connection 'db'
[2025-03-30T20:31:41.761+0000] {logging_mixin.py:190} INFO - (False,)
[2025-03-30T20:31:41.770+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T20:31:41.770+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=sales_data, task_id=ingest_sales_data, run_id=manual__2025-03-30T20:31:40.910558+00:00, execution_date=20250330T203140, start_date=20250330T203141, end_date=20250330T203141
[2025-03-30T20:31:41.836+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T20:31:41.855+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T20:31:41.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
