[2025-03-30T22:47:44.439+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:47:44.457+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [queued]>
[2025-03-30T22:47:44.463+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [queued]>
[2025-03-30T22:47:44.463+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-03-30T22:47:44.471+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_dbt> on 2025-03-30 22:43:24.831899+00:00
[2025-03-30T22:47:44.478+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'build_dbt', 'manual__2025-03-30T22:43:24.831899+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmpxgkylrue']
[2025-03-30T22:47:44.480+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=483) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:47:44.480+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask build_dbt
[2025-03-30T22:47:44.480+0000] {standard_task_runner.py:72} INFO - Started process 484 to run task
[2025-03-30T22:47:44.548+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [running]> on host 85c8af969f9d
[2025-03-30T22:47:44.606+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='build_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T22:43:24.831899+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T22:43:24.831899+00:00'
[2025-03-30T22:47:44.606+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T22:47:44.617+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T22:47:44.618+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ${AIRFLOW_HOME}/dags/dbt/hostaway_tht && dbt build --profiles-dir ./..']
[2025-03-30T22:47:44.628+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T22:47:46.096+0000] {subprocess.py:106} INFO - [0m22:47:46  Running with dbt=1.9.3
[2025-03-30T22:47:46.125+0000] {subprocess.py:106} INFO - [0m22:47:46  Encountered an error:
[2025-03-30T22:47:46.126+0000] {subprocess.py:106} INFO - Runtime Error
[2025-03-30T22:47:46.126+0000] {subprocess.py:106} INFO -   Credentials in profile "hostaway_tht", target "dev" invalid: 'port' is a required property
[2025-03-30T22:47:46.809+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-03-30T22:47:46.820+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-30T22:47:46.822+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sales_data, task_id=build_dbt, run_id=manual__2025-03-30T22:43:24.831899+00:00, execution_date=20250330T224324, start_date=20250330T224744, end_date=20250330T224746
[2025-03-30T22:47:46.846+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T22:47:46.847+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task build_dbt (Bash command failed. The command returned a non-zero exit code 2.; 484)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-30T22:47:46.869+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:47:46.887+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:47:46.888+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
