[2025-03-30T22:48:00.571+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:48:00.586+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [queued]>
[2025-03-30T22:48:00.592+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [queued]>
[2025-03-30T22:48:00.592+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 5
[2025-03-30T22:48:00.598+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_dbt> on 2025-03-30 22:43:24.831899+00:00
[2025-03-30T22:48:00.605+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=502) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:48:00.604+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'build_dbt', 'manual__2025-03-30T22:43:24.831899+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmpuf5ocme2']
[2025-03-30T22:48:00.606+0000] {standard_task_runner.py:72} INFO - Started process 503 to run task
[2025-03-30T22:48:00.606+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask build_dbt
[2025-03-30T22:48:00.641+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [running]> on host 85c8af969f9d
[2025-03-30T22:48:00.691+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='build_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T22:43:24.831899+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T22:43:24.831899+00:00'
[2025-03-30T22:48:00.692+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T22:48:00.701+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T22:48:00.702+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ${AIRFLOW_HOME}/dags/dbt/hostaway_tht && dbt build --profiles-dir ./..']
[2025-03-30T22:48:00.712+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T22:48:01.856+0000] {subprocess.py:106} INFO - [0m22:48:01  Running with dbt=1.9.3
[2025-03-30T22:48:02.066+0000] {subprocess.py:106} INFO - [0m22:48:02  Registered adapter: postgres=1.9.0
[2025-03-30T22:48:02.167+0000] {subprocess.py:106} INFO - [0m22:48:02  Unable to do partial parsing because profile has changed
[2025-03-30T22:48:03.003+0000] {subprocess.py:106} INFO - [0m22:48:03  Found 1 model, 5 data tests, 1 source, 434 macros
[2025-03-30T22:48:03.005+0000] {subprocess.py:106} INFO - [0m22:48:03
[2025-03-30T22:48:03.005+0000] {subprocess.py:106} INFO - [0m22:48:03  Concurrency: 1 threads (target='dev')
[2025-03-30T22:48:03.005+0000] {subprocess.py:106} INFO - [0m22:48:03
[2025-03-30T22:48:03.109+0000] {subprocess.py:106} INFO - [0m22:48:03  1 of 6 START sql view model staging.staging__sales ............................. [RUN]
[2025-03-30T22:48:03.161+0000] {subprocess.py:106} INFO - [0m22:48:03  1 of 6 ERROR creating sql view model staging.staging__sales .................... [[31mERROR[0m in 0.05s]
[2025-03-30T22:48:03.164+0000] {subprocess.py:106} INFO - [0m22:48:03  2 of 6 SKIP test accepted_values_staging__sales_channel__Offline__Online ....... [[33mSKIP[0m]
[2025-03-30T22:48:03.165+0000] {subprocess.py:106} INFO - [0m22:48:03  3 of 6 SKIP test not_null_staging__sales_id .................................... [[33mSKIP[0m]
[2025-03-30T22:48:03.166+0000] {subprocess.py:106} INFO - [0m22:48:03  4 of 6 SKIP test not_null_staging__sales_product_id ............................ [[33mSKIP[0m]
[2025-03-30T22:48:03.168+0000] {subprocess.py:106} INFO - [0m22:48:03  5 of 6 SKIP test not_null_staging__sales_retailer_id ........................... [[33mSKIP[0m]
[2025-03-30T22:48:03.169+0000] {subprocess.py:106} INFO - [0m22:48:03  6 of 6 SKIP test unique_staging__sales_id ...................................... [[33mSKIP[0m]
[2025-03-30T22:48:03.183+0000] {subprocess.py:106} INFO - [0m22:48:03
[2025-03-30T22:48:03.183+0000] {subprocess.py:106} INFO - [0m22:48:03  Finished running 5 data tests, 1 view model in 0 hours 0 minutes and 0.18 seconds (0.18s).
[2025-03-30T22:48:03.209+0000] {subprocess.py:106} INFO - [0m22:48:03
[2025-03-30T22:48:03.209+0000] {subprocess.py:106} INFO - [0m22:48:03  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-03-30T22:48:03.210+0000] {subprocess.py:106} INFO - [0m22:48:03
[2025-03-30T22:48:03.210+0000] {subprocess.py:106} INFO - [0m22:48:03    Database Error in model staging__sales (models/staging/staging__sales.sql)
[2025-03-30T22:48:03.210+0000] {subprocess.py:106} INFO -   syntax error at or near "from"
[2025-03-30T22:48:03.210+0000] {subprocess.py:106} INFO -   LINE 22: from
[2025-03-30T22:48:03.210+0000] {subprocess.py:106} INFO -            ^
[2025-03-30T22:48:03.211+0000] {subprocess.py:106} INFO -   compiled code at target/run/hostaway_tht/models/staging/staging__sales.sql
[2025-03-30T22:48:03.211+0000] {subprocess.py:106} INFO - [0m22:48:03
[2025-03-30T22:48:03.211+0000] {subprocess.py:106} INFO - [0m22:48:03  Done. PASS=0 WARN=0 ERROR=1 SKIP=5 TOTAL=6
[2025-03-30T22:48:03.961+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-30T22:48:03.979+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T22:48:03.983+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sales_data, task_id=build_dbt, run_id=manual__2025-03-30T22:43:24.831899+00:00, execution_date=20250330T224324, start_date=20250330T224800, end_date=20250330T224803
[2025-03-30T22:48:04.008+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T22:48:04.008+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 56 for task build_dbt (Bash command failed. The command returned a non-zero exit code 1.; 503)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T22:48:04.021+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:48:04.040+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:48:04.041+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
