[2025-03-30T22:48:27.766+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:48:27.782+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [queued]>
[2025-03-30T22:48:27.787+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [queued]>
[2025-03-30T22:48:27.788+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 6
[2025-03-30T22:48:27.794+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_dbt> on 2025-03-30 22:43:24.831899+00:00
[2025-03-30T22:48:27.803+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=539) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:48:27.801+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'build_dbt', 'manual__2025-03-30T22:43:24.831899+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmpvom6p64m']
[2025-03-30T22:48:27.804+0000] {standard_task_runner.py:72} INFO - Started process 540 to run task
[2025-03-30T22:48:27.804+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask build_dbt
[2025-03-30T22:48:27.843+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.build_dbt manual__2025-03-30T22:43:24.831899+00:00 [running]> on host 85c8af969f9d
[2025-03-30T22:48:27.900+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='build_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T22:43:24.831899+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T22:43:24.831899+00:00'
[2025-03-30T22:48:27.900+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T22:48:27.911+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T22:48:27.912+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ${AIRFLOW_HOME}/dags/dbt/hostaway_tht && dbt build --profiles-dir ./..']
[2025-03-30T22:48:27.920+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T22:48:29.196+0000] {subprocess.py:106} INFO - [0m22:48:29  Running with dbt=1.9.3
[2025-03-30T22:48:29.320+0000] {subprocess.py:106} INFO - [0m22:48:29  Registered adapter: postgres=1.9.0
[2025-03-30T22:48:29.730+0000] {subprocess.py:106} INFO - [0m22:48:29  Found 1 model, 5 data tests, 1 source, 434 macros
[2025-03-30T22:48:29.731+0000] {subprocess.py:106} INFO - [0m22:48:29
[2025-03-30T22:48:29.732+0000] {subprocess.py:106} INFO - [0m22:48:29  Concurrency: 1 threads (target='dev')
[2025-03-30T22:48:29.732+0000] {subprocess.py:106} INFO - [0m22:48:29
[2025-03-30T22:48:29.800+0000] {subprocess.py:106} INFO - [0m22:48:29  1 of 6 START sql view model staging.staging__sales ............................. [RUN]
[2025-03-30T22:48:29.843+0000] {subprocess.py:106} INFO - [0m22:48:29  1 of 6 ERROR creating sql view model staging.staging__sales .................... [[31mERROR[0m in 0.04s]
[2025-03-30T22:48:29.845+0000] {subprocess.py:106} INFO - [0m22:48:29  2 of 6 SKIP test accepted_values_staging__sales_channel__Offline__Online ....... [[33mSKIP[0m]
[2025-03-30T22:48:29.846+0000] {subprocess.py:106} INFO - [0m22:48:29  3 of 6 SKIP test not_null_staging__sales_id .................................... [[33mSKIP[0m]
[2025-03-30T22:48:29.847+0000] {subprocess.py:106} INFO - [0m22:48:29  4 of 6 SKIP test not_null_staging__sales_product_id ............................ [[33mSKIP[0m]
[2025-03-30T22:48:29.849+0000] {subprocess.py:106} INFO - [0m22:48:29  5 of 6 SKIP test not_null_staging__sales_retailer_id ........................... [[33mSKIP[0m]
[2025-03-30T22:48:29.850+0000] {subprocess.py:106} INFO - [0m22:48:29  6 of 6 SKIP test unique_staging__sales_id ...................................... [[33mSKIP[0m]
[2025-03-30T22:48:29.861+0000] {subprocess.py:106} INFO - [0m22:48:29
[2025-03-30T22:48:29.861+0000] {subprocess.py:106} INFO - [0m22:48:29  Finished running 5 data tests, 1 view model in 0 hours 0 minutes and 0.13 seconds (0.13s).
[2025-03-30T22:48:29.886+0000] {subprocess.py:106} INFO - [0m22:48:29
[2025-03-30T22:48:29.887+0000] {subprocess.py:106} INFO - [0m22:48:29  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-03-30T22:48:29.887+0000] {subprocess.py:106} INFO - [0m22:48:29
[2025-03-30T22:48:29.887+0000] {subprocess.py:106} INFO - [0m22:48:29    Database Error in model staging__sales (models/staging/staging__sales.sql)
[2025-03-30T22:48:29.888+0000] {subprocess.py:106} INFO -   column "RetailedName" does not exist
[2025-03-30T22:48:29.888+0000] {subprocess.py:106} INFO -   LINE 16:     "RetailedName" as retailer_name,
[2025-03-30T22:48:29.888+0000] {subprocess.py:106} INFO -                ^
[2025-03-30T22:48:29.888+0000] {subprocess.py:106} INFO -   HINT:  Perhaps you meant to reference the column "sales.RetailerName".
[2025-03-30T22:48:29.888+0000] {subprocess.py:106} INFO -   compiled code at target/run/hostaway_tht/models/staging/staging__sales.sql
[2025-03-30T22:48:29.888+0000] {subprocess.py:106} INFO - [0m22:48:29
[2025-03-30T22:48:29.889+0000] {subprocess.py:106} INFO - [0m22:48:29  Done. PASS=0 WARN=0 ERROR=1 SKIP=5 TOTAL=6
[2025-03-30T22:48:30.614+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-30T22:48:30.643+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T22:48:30.647+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sales_data, task_id=build_dbt, run_id=manual__2025-03-30T22:43:24.831899+00:00, execution_date=20250330T224324, start_date=20250330T224827, end_date=20250330T224830
[2025-03-30T22:48:30.709+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T22:48:30.712+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task build_dbt (Bash command failed. The command returned a non-zero exit code 1.; 540)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T22:48:30.776+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:48:30.806+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:48:30.807+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
