[2025-03-31T00:00:01.302+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T00:00:01.317+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.ingest_sales_data scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T00:00:01.322+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.ingest_sales_data scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T00:00:01.322+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T00:00:01.329+0000] {taskinstance.py:2890} INFO - Executing <Task(SalesIngestionOperator): ingest_sales_data> on 2025-03-30 00:00:00+00:00
[2025-03-31T00:00:01.341+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=688) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T00:00:01.339+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'ingest_sales_data', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmp9sbn6gl3']
[2025-03-31T00:00:01.341+0000] {standard_task_runner.py:72} INFO - Started process 689 to run task
[2025-03-31T00:00:01.342+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask ingest_sales_data
[2025-03-31T00:00:01.441+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.ingest_sales_data scheduled__2025-03-30T00:00:00+00:00 [running]> on host e52df2a83a37
[2025-03-31T00:00:01.514+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='ingest_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T00:00:01.514+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T00:00:01.565+0000] {logging_mixin.py:190} INFO -       SaleID  ProductID   ProductName  ... Quantity   Price       Date
0          1          1        Laptop  ...        3  4500.0 2024-02-05
1          2          2  Coffee Maker  ...        1   100.0 2024-02-24
2          3          5       Blender  ...        4   800.0 2024-02-10
3          4          1        Laptop  ...        2  3000.0 2024-02-26
4          5          2  Coffee Maker  ...        1   100.0 2024-02-09
...      ...        ...           ...  ...      ...     ...        ...
1000     996          3    Smartphone  ...        4  3200.0 2024-02-04
1001     997          3    Smartphone  ...        5  4000.0 2024-02-22
1002     998          2  Coffee Maker  ...        1   100.0 2024-02-13
1003     999          2  Coffee Maker  ...        1   100.0 2024-02-20
1004    1000          1        Laptop  ...        5  7500.0 2024-01-31

[1005 rows x 12 columns]
[2025-03-31T00:00:01.566+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (LocalFilesystemBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 317, in get_connection
    if conn_id in self._local_connections:
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 314, in _local_connections
    return load_connections_dict(self.connections_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 266, in load_connections_dict
    secrets: dict[str, Any] = _parse_secret_file(file_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 163, in _parse_secret_file
    raise AirflowException(
airflow.exceptions.AirflowException: File /opt/secrets/connections.yaml was not found. Check the configuration of your Secrets backend.
[2025-03-31T00:00:01.579+0000] {base.py:84} INFO - Retrieving connection 'db'
[2025-03-31T00:00:01.600+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (LocalFilesystemBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 317, in get_connection
    if conn_id in self._local_connections:
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 314, in _local_connections
    return load_connections_dict(self.connections_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 266, in load_connections_dict
    secrets: dict[str, Any] = _parse_secret_file(file_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 163, in _parse_secret_file
    raise AirflowException(
airflow.exceptions.AirflowException: File /opt/secrets/connections.yaml was not found. Check the configuration of your Secrets backend.
[2025-03-31T00:00:01.609+0000] {base.py:84} INFO - Retrieving connection 'db'
[2025-03-31T00:00:01.738+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T00:00:01.738+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=sales_data, task_id=ingest_sales_data, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T000001, end_date=20250331T000001
[2025-03-31T00:00:01.772+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T00:00:01.794+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T00:00:01.795+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
